"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Plus, RotateCcw, Search } from "lucide-react";
import { PageHeader } from "../components/PageHeader";import { ProductTable } from "../components/ProductTable";import { EmptyState } from "../components/EmptyState";import { LoadingState } from "../components/LoadingState";import { productsApi } from "../lib/api";import { alerts } from "../lib/alerts";import type { PaginationMeta, Product } from "../types/product";
const emptyMeta:PaginationMeta={page:1,limit:20,total:0,totalPages:0,hasPreviousPage:false,hasNextPage:false};
export default function ProductsPage(){const[products,setProducts]=useState<Product[]>([]);const[meta,setMeta]=useState(emptyMeta);const[loading,setLoading]=useState(true);const[search,setSearch]=useState("");const[debounced,setDebounced]=useState("");const[area,setArea]=useState("");const[status,setStatus]=useState("");const[pricing,setPricing]=useState("");const[sort,setSort]=useState("displayOrder");const[page,setPage]=useState(1);
 useEffect(()=>{const t=setTimeout(()=>{setDebounced(search);setPage(1)},350);return()=>clearTimeout(t)},[search]);
 const params=useMemo(()=>{const p=new URLSearchParams({page:String(page),limit:"20",sortBy:sort,sortOrder:sort==="updatedAt"?"desc":"asc"});if(debounced)p.set("search",debounced);if(area)p.set("area",area);if(status)p.set("isActive",status);if(pricing)p.set("pricingType",pricing);return p},[page,sort,debounced,area,status,pricing]);
 const load=useCallback(async()=>{try{setLoading(true);const r=await productsApi.list(params);setProducts(r.data);setMeta(r.pagination)}catch(e){alerts.error("No se pudieron cargar los productos",e instanceof Error?e.message:undefined)}finally{setLoading(false)}},[params]);useEffect(()=>{load()},[load]);
 const statusAction=async(p:Product)=>{const r=await alerts.confirm(p.isActive?"¿Desactivar producto?":"¿Activar producto?",p.isActive?"Dejará de aparecer en el catálogo activo.":"Volverá a estar disponible para cotizaciones.",p.isActive?"Desactivar":"Activar");if(!r.isConfirmed)return;try{alerts.loading("Actualizando estado...");await productsApi.status(p.id,!p.isActive);alerts.close();await load();alerts.success("Estado actualizado") }catch(e){alerts.close();alerts.error("No se pudo actualizar",e instanceof Error?e.message:undefined)}};
 const duplicate=async(p:Product)=>{const r=await alerts.confirm("¿Duplicar producto?",`Se creará una copia inactiva de “${p.name}”.`,"Duplicar");if(!r.isConfirmed)return;try{alerts.loading("Duplicando producto...");await productsApi.duplicate(p.id);alerts.close();await load();alerts.success("Producto duplicado","La copia se creó como inactiva.")}catch(e){alerts.close();alerts.error("No se pudo duplicar",e instanceof Error?e.message:undefined)}};
 const remove=async(p:Product)=>{const r=await alerts.confirm("Eliminar permanentemente",`Esta acción eliminará “${p.name}” y no se puede deshacer.`,"Sí, eliminar");if(!r.isConfirmed)return;try{alerts.loading("Eliminando producto...");await productsApi.remove(p.id);alerts.close();await load();alerts.success("Producto eliminado")}catch(e){alerts.close();alerts.error("No se pudo eliminar",e instanceof Error?e.message:undefined)}};
 const reset=()=>{setSearch("");setArea("");setStatus("");setPricing("");setSort("displayOrder");setPage(1)};
 return <><PageHeader eyebrow="Catálogo" title="Productos y servicios" description="Administra precios, disponibilidad, modalidad de cobro y tiempos de entrega." actions={<Link href="/productos/nuevo" className="button primary"><Plus size={17}/>Nuevo producto</Link>}/><section className="card filters-card"><div className="search-box"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nombre, código o descripción..."/></div><select value={area} onChange={e=>{setArea(e.target.value);setPage(1)}}><option value="">Todas las áreas</option><option value="DESIGN">Diseño</option><option value="DEVELOPMENT">Desarrollo</option></select><select value={pricing} onChange={e=>{setPricing(e.target.value);setPage(1)}}><option value="">Todos los precios</option><option value="PER_UNIT">Por unidad</option><option value="FIXED">Precio fijo</option><option value="RECURRING">Recurrente</option></select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Todos los estados</option><option value="true">Activos</option><option value="false">Inactivos</option></select><select value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="displayOrder">Orden del catálogo</option><option value="name">Nombre</option><option value="basePrice">Precio</option><option value="updatedAt">Actualización reciente</option></select><button className="icon-button reset-button" title="Limpiar filtros" onClick={reset}><RotateCcw size={18}/></button></section><section className="card table-card"><div className="table-summary"><span><strong>{meta.total}</strong> productos encontrados</span><span>Página {meta.page} de {Math.max(meta.totalPages,1)}</span></div>{loading?<LoadingState rows={7}/>:products.length?<ProductTable products={products} onStatus={statusAction} onDuplicate={duplicate} onDelete={remove}/>:<EmptyState action={<Link href="/productos/nuevo" className="button primary"><Plus size={17}/>Crear producto</Link>}/>}<div className="pagination"><button className="button secondary compact" disabled={!meta.hasPreviousPage} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/>Anterior</button><span>{meta.total?`${(meta.page-1)*meta.limit+1}-${Math.min(meta.page*meta.limit,meta.total)} de ${meta.total}`:"0 resultados"}</span><button className="button secondary compact" disabled={!meta.hasNextPage} onClick={()=>setPage(p=>p+1)}>Siguiente<ChevronRight size={17}/></button></div></section></>}
